# Generated by Django 5.1.1 on 2024-10-16 21:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(max_length=255, upload_to='xeber')),
                ('category', models.CharField(max_length=255)),
                ('ana_sayfa', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
